### ISSUE TITLE
EXC_BAD_ACESS (code=2, address=0x 10)

### ISSUE THREAD

**Issue by lazerbolt390** [MakeSchool/PeevedPenguins-Spritebuilder#4]
I am doing an online makegameswithus course but it has this error EXC_BAD_ACESS (code=2, address=0x 10) in PeevedPenguns>libs>cocos2d-ios.xcodeproj>cocos2d>Actions>CCActioninterval.m

**Comment by Ben-G** [comment]
@lazerbolt390 I'm sorry we missed this issue on this repository. Are still having this issue? If so, can you discuss it on https://discourse.makeschool.com/ by opening a new topic? That's a better place for this kind of question, since it's not related to this GitHub project.

Thanks!

**Comment by lazerbolt390** [comment]
Yes

Sincerely,
Manish
